"""aading stripe id to user

Revision ID: 01bcec1adc62
Revises: 00841d8698f1
Create Date: 2025-03-24 12:02:08.544891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bcec1adc62'
down_revision: Union[str, None] = '00841d8698f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.drop_column('user', 'strip_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('strip_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
