"""Updating user with stripe id

Revision ID: b2ccd1b6531e
Revises: 576156ed3210
Create Date: 2025-03-24 11:06:53.662464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ccd1b6531e'
down_revision: Union[str, None] = '576156ed3210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('strip_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'strip_customer_id')
    # ### end Alembic commands ###
